#ifndef _LAYO_H
#define _LAYO_H

#include "main.h"

#define GAP 20
#define TOP_LINE_WIDTH 60
#define BOT_LINE_WIDTH 50
#define MED_LINE_WIDTH 220

#define DARK_COLOR LCD_COLOR_BLUE
#define LIGHT_COLOR LCD_COLOR_WHITEBLUE
#define MID_COLOR LCD_COLOR_WHITE

//Public defines mainbar sizers
#define MAINBAR_POS_X 0
#define MAINBAR_POS_Y 0
#define MAINBAR_SIZE_X BSP_LCD_GetXSize()
#define MAINBAR_SIZE_Y TOP_LINE_WIDTH

#define RETURN_BUT_POS_X 0
#define RETURN_BUT_POS_Y 0
#define RETURN_BUT_SIZE_X 100
#define RETURN_BUT_SIZE_Y TOP_LINE_WIDTH

#define HOME_BUT_X 430
#define HOME_BUT_Y 0

#define MODE_STATUS_TEXT_X 105
#define MODE_STATUS_TEXT_Y 16

#define SMALL_LOGO_X  430
#define SMALL_LOGO_Y  10

//Public defines statusbar sizers
#define STATUSBAR_POS_X 0
#define STATUSBAR_POS_Y BSP_LCD_GetYSize() - TOP_LINE_WIDTH + 20
#define STATUSBAR_SIZE_X BSP_LCD_GetXSize()
#define STATUSBAR_SIZE_Y TOP_LINE_WIDTH - 20

#define SAVE_X 330
#define SAVE_Y TOP_LINE_WIDTH + MED_LINE_WIDTH + 5

#define CANCEL_X 90
#define CANCEL_Y TOP_LINE_WIDTH + MED_LINE_WIDTH + 5

#define OK_X 290
#define OK_Y TOP_LINE_WIDTH + MED_LINE_WIDTH + 5

#define TEXT_X 30
#define TEXT_Y TOP_LINE_WIDTH + MED_LINE_WIDTH + 5

//Public defines main window sizers
#define MAIN_WINDOW_POS_X 0
#define MAIN_WINDOW_POS_Y TOP_LINE_WIDTH
#define MAIN_WINDOW_SIZE_X BSP_LCD_GetXSize()
#define MAIN_WINDOW_SIZE_Y MED_LINE_WIDTH


//Public defines lists sizers
#define STATIC_LINE_X 18
#define STATIC_LINE_Y TOP_LINE_WIDTH + 9
#define STATIC_LINE_SPASER (BSP_LCD_GetYSize() - TOP_LINE_WIDTH - BOT_LINE_WIDTH - 30)/4

#define FIRST_CURSOR_POS_X STATIC_LINE_X - 9
#define FIRST_CURSOR_POS_Y STATIC_LINE_Y
#define FIRST_CURSOR_SIZE_X 350
#define FIRST_CURSOR_SIZE_Y STATIC_LINE_SPASER

#define SECOND_CURSOR_POS_X FIRST_CURSOR_POS_X
#define SECOND_CURSOR_POS_Y STATIC_LINE_Y + STATIC_LINE_SPASER
#define SECOND_CURSOR_SIZE_X FIRST_CURSOR_SIZE_X
#define SECOND_CURSOR_SIZE_Y STATIC_LINE_SPASER

#define THRID_CURSOR_POS_X FIRST_CURSOR_POS_X
#define THRID_CURSOR_POS_Y STATIC_LINE_Y + STATIC_LINE_SPASER * 2
#define THRID_CURSOR_SIZE_X FIRST_CURSOR_SIZE_X
#define THRID_CURSOR_SIZE_Y STATIC_LINE_SPASER

#define FOURTH_CURSOR_POS_X FIRST_CURSOR_POS_X
#define FOURTH_CURSOR_POS_Y STATIC_LINE_Y + STATIC_LINE_SPASER * 3
#define FOURTH_CURSOR_SIZE_X FIRST_CURSOR_SIZE_X
#define FOURTH_CURSOR_SIZE_Y STATIC_LINE_SPASER  

#define FIRST_CURSOR_VALUE_BOX_X 210
#define FIRST_CURSOR_VALUE_BOX_Y TOP_LINE_WIDTH
#define FIRST_CURSOR_VALUE_BOX_SIZE_X 80
#define FIRST_CURSOR_VALUE_BOX_SIZE_Y 66

#define SECOND_CURSOR_VALUE_BOX_X 210
#define SECOND_CURSOR_VALUE_BOX_Y FIRST_CURSOR_VALUE_BOX_Y + 68
#define SECOND_CURSOR_VALUE_BOX_SIZE_X FIRST_CURSOR_VALUE_BOX_SIZE_X
#define SECOND_CURSOR_VALUE_BOX_SIZE_Y FIRST_CURSOR_VALUE_BOX_SIZE_Y 

#define THRID_CURSOR_VALUE_BOX_X 210
#define THRID_CURSOR_VALUE_BOX_Y SECOND_CURSOR_VALUE_BOX_Y + 68
#define THRID_CURSOR_VALUE_BOX_SIZE_X FIRST_CURSOR_VALUE_BOX_SIZE_X
#define THRID_CURSOR_VALUE_BOX_SIZE_Y FIRST_CURSOR_VALUE_BOX_SIZE_Y - 20


//Public defines scroll sizers
#define SCROLLBAR_POS_X 390
#define SCROLLBAR_POS_Y TOP_LINE_WIDTH + 9
#define SCROLLBAR_SIZE_X TOP_LINE_WIDTH - 5
#define SCROLLBAR_SIZE_Y 202  

#define SCROLLKEYUP_POS_X 416
#define SCROLLKEYUP_POS_Y TOP_LINE_WIDTH + 9
#define SCROLLKEYUP_SIZE_X TOP_LINE_WIDTH - 5
#define SCROLLKEYUP_SIZE_Y 50 

#define SCROLLKEYDOWN_POS_X SCROLLKEYUP_POS_X
#define SCROLLKEYDOWN_POS_Y TOP_LINE_WIDTH + 161
#define SCROLLKEYDOWN_SIZE_X TOP_LINE_WIDTH - 5
#define SCROLLKEYDOWN_SIZE_Y 50 

#define SCROLLBAR_RADIUS 10

#define UP_ARROW_POS_X SCROLLKEYUP_POS_X - 5
#define UP_ARROW_POS_Y SCROLLBAR_POS_Y
#define UP_ARROW_SIZE_X TOP_LINE_WIDTH
#define UP_ARROW_SIZE_Y TOP_LINE_WIDTH - 9

#define DOWN_ARROW_POS_X SCROLLKEYDOWN_POS_X - 5
#define DOWN_ARROW_POS_Y UP_ARROW_POS_Y + 155
#define DOWN_ARROW_SIZE_X TOP_LINE_WIDTH
#define DOWN_ARROW_SIZE_Y UP_ARROW_SIZE_Y - 2

#define SCROLLBAR_CURSOR_POS_X SCROLLBAR_POS_X + 10
#define SCROLLBAR_CURSOR_POS_Y SCROLLBAR_POS_Y + 30
#define SCROLLBAR_CURSOR_SIZE_X 30
#define SCROLLBAR_CURSOR_SIZE_Y 50
#define SCROLLBAR_CURSOR_RADIUS 15

#define SCROLLBAR_CURSOR_SLIDER_POS_X SCROLLBAR_CURSOR_POS_X + 5
#define SCROLLBAR_CURSOR_SLIDER_POS_Y SCROLLBAR_CURSOR_POS_Y + 5
#define SCROLLBAR_CURSOR_SLIDER_SIZE_X TOP_LINE_WIDTH - 10
#define SCROLLBAR_CURSOR_SLIDER_SIZE_Y 5

//Clock defines
#define CLOCK_X 390
#define CLOCK_Y TEXT_Y //+ 24
#define HOUR_X CLOCK_X
#define MINUTE_X CLOCK_X + 2 * 15 + 10
#define DIV_X CLOCK_X + 2 * 15

//keyboard defines
#define TEXT_CTRL_POS_X 40
#define TEXT_CTRL_POS_Y TOP_LINE_WIDTH + 30
#define TEXT_CTRL_SIZE_X 400
#define TEXT_CTRL_SIZE_Y BOT_LINE_WIDTH

#define CURSOR_POS_X TEXT_CTRL_POS_X + 10
#define CURSOR_POS_Y TEXT_CTRL_POS_Y + 5
#define CURSOR_SIZE_X 2
#define CURSOR_SIZE_Y 40

#define LINE_KEYS_POS_X 0
#define LINE_KEYS_POS_Y (TOP_LINE_WIDTH * 2) + 49

#define NUM_KEYS_POS_X 25
#define NUM_KEYS_POS_Y LINE_KEYS_POS_Y + 4

#define OK "СОХРАНИТЬ"
#define CANCEL "НАЗАД"
    
#endif 