<<<<<<< Updated upstream

/*
 * Auto generated Run-Time-Environment Configuration File
 *      *** Do not modify ! ***
=======
/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
>>>>>>> Stashed changes
 *
 * Project: 'SPO' 
 * Target:  'GD_Prod_Test' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


<<<<<<< Updated upstream
/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "gd32f30x.h"


=======
>>>>>>> Stashed changes

#endif /* RTE_COMPONENTS_H */
