#ifndef _LAYO_H
#define _LAYO_H


#include "main.h"

#define TOP_BOT_LINE_WIDTH 60
#define MED_LINE_WIDTH 220


//Public defines mainbar sizers
#define MAINBAR_POS_X 0
#define MAINBAR_POS_Y 0
#define MAINBAR_SIZE_X BSP_LCD_GetXSize()
#define MAINBAR_SIZE_Y TOP_BOT_LINE_WIDTH

#define RETURN_BUT_POS_X 0
#define RETURN_BUT_POS_Y 0
#define RETURN_BUT_SIZE_X TOP_BOT_LINE_WIDTH
#define RETURN_BUT_SIZE_Y 100

#define MODE_STATUS_TEXT_X 65
#define MODE_STATUS_TEXT_Y 13


//Public defines statusbar sizers
#define STATUSBAR_POS_X 0
#define STATUSBAR_POS_Y BSP_LCD_GetYSize() - TOP_BOT_LINE_WIDTH + 20
#define STATUSBAR_SIZE_X BSP_LCD_GetXSize()
#define STATUSBAR_SIZE_Y TOP_BOT_LINE_WIDTH - 20

#define SAVE_X 330
#define SAVE_Y TOP_BOT_LINE_WIDTH + MED_LINE_WIDTH + 3

#define CANCEL_X 110
#define CANCEL_Y TOP_BOT_LINE_WIDTH + MED_LINE_WIDTH + 3

#define OK_X 320
#define OK_Y TOP_BOT_LINE_WIDTH + MED_LINE_WIDTH + 3

#define TEXT_X 30
#define TEXT_Y TOP_BOT_LINE_WIDTH + MED_LINE_WIDTH + 3

//Public defines main window sizers
#define MAIN_WINDOW_POS_X 0
#define MAIN_WINDOW_POS_Y BSP_LCD_GetYSize() - TOP_BOT_LINE_WIDTH - MED_LINE_WIDTH
#define MAIN_WINDOW_SIZE_X BSP_LCD_GetXSize()
#define MAIN_WINDOW_SIZE_Y MED_LINE_WIDTH


//Public defines lists sizers
#define FIRST_CURSOR_POS_X 0
#define FIRST_CURSOR_POS_Y TOP_BOT_LINE_WIDTH - 1
#define FIRST_CURSOR_SIZE_X 420
#define FIRST_CURSOR_SIZE_Y 68

#define SECOND_CURSOR_POS_X 0
#define SECOND_CURSOR_POS_Y FIRST_CURSOR_POS_Y + 68
#define SECOND_CURSOR_SIZE_X FIRST_CURSOR_SIZE_X
#define SECOND_CURSOR_SIZE_Y FIRST_CURSOR_SIZE_Y

#define THRID_CURSOR_POS_X 0
#define THRID_CURSOR_POS_Y SECOND_CURSOR_POS_Y + 68
#define THRID_CURSOR_SIZE_X FIRST_CURSOR_SIZE_X
#define THRID_CURSOR_SIZE_Y FIRST_CURSOR_SIZE_Y

#define FIRST_CURSOR_VALUE_BOX_X 210
#define FIRST_CURSOR_VALUE_BOX_Y TOP_BOT_LINE_WIDTH
#define FIRST_CURSOR_VALUE_BOX_SIZE_X 80
#define FIRST_CURSOR_VALUE_BOX_SIZE_Y 66

#define SECOND_CURSOR_VALUE_BOX_X 210
#define SECOND_CURSOR_VALUE_BOX_Y FIRST_CURSOR_VALUE_BOX_Y + 68
#define SECOND_CURSOR_VALUE_BOX_SIZE_X FIRST_CURSOR_VALUE_BOX_SIZE_X
#define SECOND_CURSOR_VALUE_BOX_SIZE_Y FIRST_CURSOR_VALUE_BOX_SIZE_Y 

#define THRID_CURSOR_VALUE_BOX_X 210
#define THRID_CURSOR_VALUE_BOX_Y SECOND_CURSOR_VALUE_BOX_Y + 68
#define THRID_CURSOR_VALUE_BOX_SIZE_X FIRST_CURSOR_VALUE_BOX_SIZE_X
#define THRID_CURSOR_VALUE_BOX_SIZE_Y FIRST_CURSOR_VALUE_BOX_SIZE_Y - 2

//Public defines scroll sizers
#define SCROLLBAR_POS_X 385
#define SCROLLBAR_POS_Y TOP_BOT_LINE_WIDTH + 9
#define SCROLLBAR_SIZE_X TOP_BOT_LINE_WIDTH - 10
#define SCROLLBAR_SIZE_Y 202  
#define SCROLLBAR_RADIUS 10

#define UP_ARROW_POS_X SCROLLBAR_POS_X - 5
#define UP_ARROW_POS_Y SCROLLBAR_POS_Y
#define UP_ARROW_SIZE_X TOP_BOT_LINE_WIDTH
#define UP_ARROW_SIZE_Y TOP_BOT_LINE_WIDTH - 9

#define DOWN_ARROW_POS_X UP_ARROW_POS_X
#define DOWN_ARROW_POS_Y UP_ARROW_POS_Y + 155
#define DOWN_ARROW_SIZE_X TOP_BOT_LINE_WIDTH
#define DOWN_ARROW_SIZE_Y UP_ARROW_SIZE_Y - 2

#define SCROLLBAR_CURSOR_POS_X SCROLLBAR_POS_X + 10
#define SCROLLBAR_CURSOR_POS_Y SCROLLBAR_POS_Y + 30
#define SCROLLBAR_CURSOR_SIZE_X 30
#define SCROLLBAR_CURSOR_SIZE_Y 50
#define SCROLLBAR_CURSOR_RADIUS 15

//#define SCROLLBAR_CURSOR_SLIDER_POS_X SCROLLBAR_CURSOR_POS_X + 5
//#define SCROLLBAR_CURSOR_SLIDER_POS_Y SCROLLBAR_CURSOR_POS_Y + 5
//#define SCROLLBAR_CURSOR_SLIDER_SIZE_X TOP_BOT_LINE_WIDTH - 10
//#define SCROLLBAR_CURSOR_SLIDER_SIZE_Y 5

#define CURSOR_POS_X 50
#define CURSOR_POS_Y TOP_BOT_LINE_WIDTH + 10
#define CURSOR_SIZE_X 2
#define CURSOR_SIZE_Y 50

#endif 