#include "main.h"

//Public defines
//#define MODE_SOFTENING_CYCLE "SOFTENING CYCLE"
//#define MODE_MENU "MODE"
//#define DELAY_REGEN "DELAY REGEN"
//#define SPEED "SPEED"
//#define TIME "TIME"

#define MODE_SOFTENING_CYCLE 0
#define MODE_MENU 1
#define DELAY_REGEN 2
#define SPEED 3
#define TIME 4

//#define DELAY_REGEN_UNITS "DAYS"
//#define SPEED_UNITS "L/MIN"
//#define TIME_UNITS "HH:MM"

#define DELAY_REGEN_UNITS 5
#define SPEED_UNITS 6
#define TIME_UNITS 7

#define PL_NOT_INITED "---"

//Public defines sizers
#define TOP_BOT_LINE_WIDTH 60
#define MED_LINE_WIDTH 200
#define LIST_WIDTH TOP_BOT_LINE_WIDTH
#define LIST_TOP_BOT_SPACER (MED_LINE_WIDTH - (LIST_WIDTH * 3)) / 2 

//Public defines mainbar sizers
#define MAINBAR_POS_X 0
#define MAINBAR_POS_Y 0
#define MAINBAR_SIZE_X BSP_LCD_GetXSize()
#define MAINBAR_SIZE_Y TOP_BOT_LINE_WIDTH

#define MODE_STATUS_TEXT_X 16
#define MODE_STATUS_TEXT_Y 13

//Public defines statusbar sizers
#define STATUSBAR_POS_X 0
#define STATUSBAR_POS_Y BSP_LCD_GetYSize() - TOP_BOT_LINE_WIDTH
#define STATUSBAR_SIZE_X BSP_LCD_GetXSize()
#define STATUSBAR_SIZE_Y TOP_BOT_LINE_WIDTH

#define MODE_MENU_X 16
#define MODE_MENU_Y TOP_BOT_LINE_WIDTH + MED_LINE_WIDTH + 13

//Public defines main window sizers
#define MAIN_WINDOW_POS_X 0
#define MAIN_WINDOW_POS_Y BSP_LCD_GetYSize() - TOP_BOT_LINE_WIDTH - MED_LINE_WIDTH
#define MAIN_WINDOW_SIZE_X BSP_LCD_GetXSize()
#define MAIN_WINDOW_SIZE_Y MED_LINE_WIDTH

///////////////////////////////////////////
#define DELAY_REGEN_VALUE_BOX_X 210
#define DELAY_REGEN_VALUE_BOX_Y TOP_BOT_LINE_WIDTH + LIST_TOP_BOT_SPACER
#define DELAY_REGEN_VALUE_BOX_SIZE_X 130
#define DELAY_REGEN_VALUE_BOX_SIZE_Y LIST_WIDTH

#define SPEED_VALUE_BOX_X DELAY_REGEN_VALUE_BOX_X
#define SPEED_VALUE_BOX_Y TOP_BOT_LINE_WIDTH + LIST_TOP_BOT_SPACER + LIST_WIDTH
#define SPEED_VALUE_BOX_SIZE_X DELAY_REGEN_VALUE_BOX_SIZE_X
#define SPEED_VALUE_BOX_SIZE_Y LIST_WIDTH

#define TIME_VALUE_BOX_X DELAY_REGEN_VALUE_BOX_X
#define TIME_VALUE_BOX_Y TOP_BOT_LINE_WIDTH + LIST_TOP_BOT_SPACER + (LIST_WIDTH * 2) 
#define TIME_VALUE_BOX_SIZE_X DELAY_REGEN_VALUE_BOX_SIZE_X
#define TIME_VALUE_BOX_SIZE_Y LIST_WIDTH

///////////////////////////////////////////
#define DELAY_REGEN_STATUS_TEXT_X 26
#define DELAY_REGEN_STATUS_TEXT_Y TOP_BOT_LINE_WIDTH + LIST_TOP_BOT_SPACER + 13

#define SPEED_STATUS_TEXT_X DELAY_REGEN_STATUS_TEXT_X
#define SPEED_STATUS_TEXT_Y TOP_BOT_LINE_WIDTH + LIST_TOP_BOT_SPACER + LIST_WIDTH + 13

#define TIME_STATUS_TEXT_X DELAY_REGEN_STATUS_TEXT_X
#define TIME_STATUS_TEXT_Y TOP_BOT_LINE_WIDTH + LIST_TOP_BOT_SPACER + (LIST_WIDTH * 2) + 13

///////////////////////////////////////////
#define DELAY_REGEN_STATUS_UNITS_X 370
#define DELAY_REGEN_STATUS_UNITS_Y TOP_BOT_LINE_WIDTH + LIST_TOP_BOT_SPACER + 13

#define SPEED_STATUS_UNITS_X DELAY_REGEN_STATUS_UNITS_X
#define SPEED_STATUS_UNITS_Y TOP_BOT_LINE_WIDTH + LIST_TOP_BOT_SPACER + LIST_WIDTH + 13

#define TIME_STATUS_UNITS_X DELAY_REGEN_STATUS_UNITS_X
#define TIME_STATUS_UNITS_Y TOP_BOT_LINE_WIDTH + LIST_TOP_BOT_SPACER + (LIST_WIDTH * 2) + 13

///////////////////////////////////////////
#define DELAY_REGEN_STATUS_VALUE_X 220
#define DELAY_REGEN_STATUS_VALUE_Y TOP_BOT_LINE_WIDTH + LIST_TOP_BOT_SPACER + 13

#define SPEED_STATUS_VALUE_X DELAY_REGEN_STATUS_VALUE_X
#define SPEED_STATUS_VALUE_Y TOP_BOT_LINE_WIDTH + LIST_TOP_BOT_SPACER + LIST_WIDTH + 13

#define TIME_STATUS_VALUE_X DELAY_REGEN_STATUS_VALUE_X
#define TIME_STATUS_VALUE_Y TOP_BOT_LINE_WIDTH + LIST_TOP_BOT_SPACER + (LIST_WIDTH * 2) + 13

void ShowMainFrame(void);

void RefreshMainFrame(void);

void AnimateTimeMainFrame(void);

void TranslateMainFrameMSG (void);


