
/*
<<<<<<< Updated upstream
 * Auto generated Run-Time-Environment Configuration File
 *      *** Do not modify ! ***
=======
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
>>>>>>> Stashed changes
 *
 * Project: 'SPO' 
 * Target:  'ProductionTest' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f10x.h"



#endif /* RTE_COMPONENTS_H */
